# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e52f99e23b0274a1b68e4d2353921671eb94471089b600dc81e6967eb067d54b4e52b8e03b8517b015b81648b5ff534f0b74b2563ad327f7e01a2c644131282d

test:
  secret_key_base: cea92bf4eea778493c04248af1770b4abddbbf88e3cfcdc3f52d8c9a4038205f21f07221e17b4e2b45d98f3f7ccbcdab34f36fc425179c53a60aab6a11ac15f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
